name: Splunk AppInspect

on:
  push:
    paths:
      - 'SplunkforCiscoUmbrella/**'
  pull_request:

jobs:
  appinspect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install AppInspect
        run: |
          python -m pip install --upgrade pip
          wget http://download.splunk.com/misc/appinspect/splunk-appinspect-latest.tar.gz
          pip3 install --no-cache splunk-appinspect-latest.tar.gz
          splunk-appinspect list version

      - name: Run AppInspect
        run: splunk-appinspect inspect SplunkforCiscoUmbrella